import paramiko, sys
host=sys.argv[1]; user=sys.argv[2]; pw=sys.argv[3]; cmd=' '.join(sys.argv[4:])
ssh=paramiko.SSHClient(); ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect(host, username=user, password=pw, timeout=30)
stdin,stdout,stderr=ssh.exec_command(cmd)
out = stdout.read()
err = stderr.read()
sys.stdout.buffer.write(out)
sys.stderr.buffer.write(err)
ssh.close()
