map $ssl_preread_protocol $wg_backend {
    default tls_backend;
    ""      http_backend;
}

upstream http_backend {
    server 127.0.0.1:8789;
}

upstream tls_backend {
    server 127.0.0.1:9443;
}

server {
    listen 0.0.0.0:8787;
    proxy_pass $wg_backend;
    ssl_preread on;
}
