[Interface]
Address = 10.66.66.7/32
DNS = 1.1.1.1, 8.8.8.8
PrivateKey = MLbi7UTgW6vhWvdN+0+ETDEEDPQs9ldBrsINrlT74Wc=
Table = auto 
[Peer]
PublicKey = ayC9MnexgrRfAqHxcd7TW0DMAtt2jXizojY3mPlY5Do=
Endpoint = 45.151.183.153:443
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
